# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d3aaa33eec4bfe65eec3d5c0534cdb76ddf9ae0eb7dd34c54ea880ef6b3bad5701d233c0adfc3bd5bc06b5c61c96ea9cd3ca6a9717472588f589191e1adabb5

test:
  secret_key_base: fffef10ee9411dbe4452ec3d4ba69aed21875b757d32986cbe3530adf688469788775c2054ca10e998b2dad8d5e9bf03ab9758fc12925eef6b51cadfbe9e2837

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
